export default {
    CHANGE_SINGER_LIST: 'SINGERS/CHANGE_SINGER_LIST',
    CHANGE_PAGE_COUNT: 'SINGERS/CHANGE_PAGE_COUNT',
    SHOOT_ENTER_LOADING: 'SINGERS/SHOOT_ENTER_LOADING',
    SHOOT_PULL_UP_LOADING: 'SINGERS/SHOOT_PULL_UP_LOADING',
    SHOOT_PULL_DOWN_LOADING: 'SINGERS/SHOOT_PULL_DOWN_LOADING',
    CLOSE_ALL_LOADING: 'SINGERS/CLOSE_ALL_LOADING'
}