export default {
    UPDATE_HOT_SEARCH: 'search/UPDATE_HOT_SEARCH',
    UPDATE_INPUT_SUGGEST: 'search/UPDATE_INPUT_SUGGEST',
    UPDATE_INPUT_DEFAULT: 'search/UPDATE_INPUT_DEFAULT',
    UNSHIFT_SEARCH_HISTORY: 'search/UNSHIFT_SEARCH_HISTORY',
    CLEAR_SEARCH_HISTORY: 'search/CLEAR_SEARCH_HISTORY',
}