export default {
    SET_FULL_SCREEN: 'PLAYER/SET_FULL_SCREEN',
    SET_SHOW_SONG_LIST: 'PLAYER/SET_SHOW_SONG_LIST',
    SET_SHOW_MES: 'PLAYER/SET_SHOW_MES',
    TOGGLE_PLAYING: 'PLAYER/TOGGLE_PLAYING',
    TOGGLE_PLAY_MODE: 'PLAYER/TOGGLE_PLAY_MODE',
    UPDATE_PLAY_LIST: 'PLAYER/UPDATE_PLAY_LIST',
    REMOVE_PLAY_LIST_ITEM: 'REMOVE_PLAY_LIST_ITEM',
    CLOSE_SHOW_MES: 'PLAYER/CLOSE_SHOW_MES',
    CHANGE_CURRENT_INDEX: 'PLAYER/CHANGE_CURRENT_INDEX',
    CHANGE_PLAYING_SECOND: 'PLAYER/CHANGE_PLAYING_SECOND',
    UPDATE_SONG_LYRIC: 'PLAYER/UPDATE_SONG_LYRIC'
}